SOA/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')), # CAPTCHA
    path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))

main/urls.py
from django.urls import path

from .views import *

app_name = 'main'
urlpatterns = [
    # Парсинг авито
    path('result_avito/', result_avito, name='result_avito'),
    # Парсинг ЦИАН
    path('result_cian/', result_cian, name='result_cian'),
    # Активация польлзователя
    path('accounts/register/activate/<str:sign>', user_activate, name='register_activate'),
    # Завершение регистрации
    path('accounts/register/done/', RegisterDoneView.as_view(), name='register_done'),
    # Регистрация и отправка письма
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    # вход
    path('accounts/login/', SOALoginView.as_view(), name='login'),
    # Выход
    path('accounts/logout/', SOALogoutView.as_view(), name='logout'),
    # Сохранение шаблона
    path('accounts/profile/template/save/', template_save, name='template_save'),
    # Поиск по сохраненному шаблону
    path('accounts/profile/template/search/<int:pk>/', template_search, name='template_search'),
    # Удаление шаблона поиска
    path('accounts/profile/template/delete/<int:pk>/', template_delete, name='template_delete'),
    # Сохранение объявления в избранное
    path('accounts/profile/favorite/save/', favorite_save, name='favorite_save'),
    # Удаление объявления из избранного
    path('accounts/profile/favorite/delete/<int:pk>', favorite_delete, name='favorite_delete'),
    # Правка личных данных
    path('accounts/profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    # Удаление зарегистирированного пользователя
    path('accounts/profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    # Профиль пользователя
    path('accounts/profile/', profile, name='profile'),
    # Прака пароля пользователя
    path('accounts/password/change/', SOAPasswordChangeView.as_view(), name='password_change'),
    # Сброс пароля и задание нового
    path('accounts/password/reset/<uidb64>/<token>', SOAPasswordResetConfirmView.as_view(), name='password_reset_confirm'), 
    # Вывод формы и оправка письма сброса пароля    
    path('accounts/password/reset/', SOAPasswordResetView.as_view(), name='password_reset'), 
    # Справка
    path('help/<str:page>/', help, name='help'),
    path('', index, name='index'),        
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import Signal

from .utilities import send_activation_notification

# Модель пользователя
class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True, verbose_name='Прошел активацию?')

    class Meta(AbstractUser.Meta):
        pass

# Объявление сигнала регистрации пользователя и привязка к нему обрaботчика
user_registrated = Signal(providing_args=['instance'])

def user_registrated_dispatcher(sender, **kwargs):
    send_activation_notification(kwargs['instance'])

user_registrated.connect(user_registrated_dispatcher)

# Модель шаблонов поиска
class ST(models.Model):
    advuser = models.ForeignKey(AdvUser, on_delete=models.CASCADE, db_index=True, verbose_name='Пользователь')
    name = models.CharField(max_length=100, blank=True, verbose_name='Имя шаблона')
    rental = models.BooleanField(default=False, db_index=True, verbose_name='Аренда')
    purchase = models.BooleanField(default=False, db_index=True, verbose_name='Покупка')
    new_building = models.BooleanField(default=False, db_index=True, verbose_name='Новостройка')
    secondary = models.BooleanField(default=False, db_index=True, verbose_name='Вторичка')
    studio = models.BooleanField(default=False, db_index=True, verbose_name='Студия')
    NOF_1 = models.BooleanField(default=False, db_index=True, verbose_name='1')
    NOF_2 = models.BooleanField(default=False, db_index=True, verbose_name='2')
    NOF_3 = models.BooleanField(default=False, db_index=True, verbose_name='3')
    NOF_4 = models.BooleanField(default=False, db_index=True, verbose_name='4')
    NOF_5 = models.BooleanField(default=False, db_index=True, verbose_name='5')
    NOF_gte_6 = models.BooleanField(default=False, db_index=True, verbose_name='6+')
    price_from = models.IntegerField(null=True, blank=True, db_index=True, verbose_name='Цена от (руб.)')
    price_up_to = models.IntegerField(null=True, blank=True, db_index=True, verbose_name='Цена до (руб.)')
    Admiralteyskiy = models.BooleanField(default=False, db_index=True, verbose_name='Адмиралтейский')
    Vasileostrovskiy = models.BooleanField(default=False, db_index=True, verbose_name='Василеостровский')
    Vyborgskiy = models.BooleanField(default=False, db_index=True, verbose_name='Выборгский')
    Kalininskiy = models.BooleanField(default=False, db_index=True, verbose_name='Калининский')
    Kirovsky = models.BooleanField(default=False, db_index=True, verbose_name='Кировский')
    Kolpinsky = models.BooleanField(default=False, db_index=True, verbose_name='Колпинский')
    Krasnogvardeisky = models.BooleanField(default=False, db_index=True, verbose_name='Красногвардейский')
    Krasnoselsky = models.BooleanField(default=False, db_index=True, verbose_name='Красносельский')
    Kronshtadtskiy = models.BooleanField(default=False, db_index=True, verbose_name='Кронштадтский')
    Kurortnyy = models.BooleanField(default=False, db_index=True, verbose_name='Курортный')
    Moskovskiy = models.BooleanField(default=False, db_index=True, verbose_name='Московский')
    Nevsky = models.BooleanField(default=False, db_index=True, verbose_name='Невский')
    Petrogradsky = models.BooleanField(default=False, db_index=True, verbose_name='Петроградский')
    Petrodvortsovyy = models.BooleanField(default=False, db_index=True, verbose_name='Петродворцовый')
    Primorskiy = models.BooleanField(default=False, db_index=True, verbose_name='Приморский')
    Pushkinskiy = models.BooleanField(default=False, db_index=True, verbose_name='Пушкинский')
    Frunzenskiy = models.BooleanField(default=False, db_index=True, verbose_name='Фрунзенский')
    Tsentralnyy = models.BooleanField(default=False, db_index=True, verbose_name='Центральный')
    saved_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата сохранения')

    class Meta:
        verbose_name = 'Шаблон поиска'
        verbose_name_plural = 'Шаблоны поиска'

    def __str__(self):
        return self.name

# Модель избранных объявлений
class FA(models.Model):
    advuser = models.ForeignKey(AdvUser, on_delete=models.CASCADE, db_index=True, verbose_name='Пользователь')
    title = models.CharField(max_length=100, verbose_name='Заголовок объявления')
    link = models.URLField(verbose_name='Избранное объявление')
    image = models.URLField(verbose_name='Изображение')
    price = models.CharField(max_length=50, verbose_name='Цена')
    address = models.CharField(max_length=100, verbose_name='Адрес')
    date = models.CharField(max_length=50, verbose_name='Дата публикации объявления')
    agency = models.CharField(max_length=50, verbose_name='Агенство')
    saved_at = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='Дата сохранения')

    class Meta:
        verbose_name = 'Избранное объявление'
        verbose_name_plural = 'Избранные объявления'

    def __str__(self):
        return self.title

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordResetView, PasswordResetConfirmView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin 
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.base import TemplateView
from django.urls import reverse_lazy
from django.core.signing import BadSignature
from django.core.paginator import Paginator

from .models import *
from .forms import *
from .utilities import signer
from .parsers.avito import parsing_avito
from .parsers.cian import parsing_cian


# Главная страница
def index(request):
    context = {'form': UserSearchForm, 'captcha': CaptchaForm}
    return render(request, 'main/index.html', context)

# Парсинг авито
def result_avito(request):
    if request.method == 'POST':
        if not request.user.is_authenticated and 'captcha' not in request.session:
            post_params = UserSearchForm(request.POST)
            post_captcha = CaptchaForm(request.POST)
            valid = post_params.is_valid() and post_captcha.is_valid()
        else:
            post_params = UserSearchForm(request.POST)
            post_captcha = CaptchaForm
            valid = post_params.is_valid()
        if valid:
            request.session['captcha'] = 1
            global P, ADS
            P = post_params
            ADS = parsing_avito(post_params.cleaned_data)
            paginator = Paginator(ADS, 10)
            page = paginator.get_page(1)
            context = {'form': P, 'captcha': CaptchaForm, 'name': SearchNameForm, 'ads': page.object_list, 'page': page}
            return render(request, 'main/result_avito.html', context)
        else:
            context = {'form': post_params, 'captcha': post_captcha}
            return render(request, 'main/index.html', context)
    else:
        paginator = Paginator(ADS, 10)

        if 'page' in request.GET:
            page_num = request.GET['page']
        else:
            page_num = 1
        page = paginator.get_page(page_num)
        context = {'form': P, 'captcha': CaptchaForm, 'name': SearchNameForm, 'ads': page.object_list, 'page': page}
        return render(request, 'main/result_avito.html', context)


# Парсинг ЦИАН
def result_cian(request):
    if request.method == 'POST':
        if not request.user.is_authenticated and 'captcha' not in request.session:
            post_params = UserSearchForm(request.POST)
            post_captcha = CaptchaForm(request.POST)
            valid = post_params.is_valid() and post_captcha.is_valid()
        else:
            post_params = UserSearchForm(request.POST)
            post_captcha = CaptchaForm
            valid = post_params.is_valid()
        if valid:
            request.session['captcha'] = 1
            global P, ADS
            P = post_params
            ADS = parsing_cian(post_params.cleaned_data)
            paginator = Paginator(ADS, 10)
            page = paginator.get_page(1)
            context = {'form': P, 'captcha': CaptchaForm, 'name': SearchNameForm, 'ads': page.object_list, 'page': page}
            return render(request, 'main/result_cian.html', context)
        else:
            context = {'form': post_params, 'captcha': post_captcha}
            return render(request, 'main/index.html', context)
    else:
        paginator = Paginator(ADS, 10)

        if 'page' in request.GET:
            page_num = request.GET['page']
        else:
            page_num = 1
        page = paginator.get_page(page_num)
        context = {'form': P, 'captcha': CaptchaForm, 'name': SearchNameForm, 'ads': page.object_list, 'page': page}
        return render(request, 'main/result_cian.html', context)

# Сохранение шаблона поиска
@login_required
def template_save(request):
    post = UserSearchForm(request.POST)
    if post.is_valid():
        s = ST()
        s.advuser = request.user
        if 'rental' in post.cleaned_data['type_of_transaction']:
            s.rental = True
        if 'purchase' in post.cleaned_data['type_of_transaction']:
            s.purchase = True
        if 'new_building' in post.cleaned_data['novelty']:
            s.new_building = True
        if 'secondary' in post.cleaned_data['novelty']:
            s.secondary = True
        if 0 in post.cleaned_data['number_of_rooms']:
            s.studio = True
        if 1 in post.cleaned_data['number_of_rooms']:
            s.NOF_1 = True
        if 2 in post.cleaned_data['number_of_rooms']:
            s.NOF_2 = True
        if 3 in post.cleaned_data['number_of_rooms']:
            s.NOF_3 = True
        if 4 in post.cleaned_data['number_of_rooms']:
            s.NOF_4 = True
        if 5 in post.cleaned_data['number_of_rooms']:
            s.NOF_5 = True
        if 6 in post.cleaned_data['number_of_rooms']:
            s.NOF_gte_6 = True
        s.price_from = post.cleaned_data['price_from']
        s.price_up_to = post.cleaned_data['price_up_to']
        if 'Admiralteyskiy' in post.cleaned_data['district']:
            s.Admiralteyskiy = True
        if 'Vasileostrovskiy' in post.cleaned_data['district']:
            s.Vasileostrovskiy = True
        if 'Vyborgskiy' in post.cleaned_data['district']:
            s.Vyborgskiy = True
        if 'Kalininskiy' in post.cleaned_data['district']:
            s.Kalininskiy = True
        if 'Kirovsky' in post.cleaned_data['district']:
            s.Kirovsky = True
        if 'Kolpinsky' in post.cleaned_data['district']:
            s.Kolpinsky = True
        if 'Krasnogvardeisky' in post.cleaned_data['district']:
            s.Krasnogvardeisky = True
        if 'Krasnoselsky' in post.cleaned_data['district']:
            s.Krasnoselsky = True
        if 'Kronshtadtskiy' in post.cleaned_data['district']:
            s.Kronshtadtskiy = True
        if 'Kurortnyy' in post.cleaned_data['district']:
            s.Kurortnyy = True
        if 'Moskovskiy' in post.cleaned_data['district']:
            s.Moskovskiy = True
        if 'Nevsky' in post.cleaned_data['district']:
            s.Nevsky = True
        if 'Petrogradsky' in post.cleaned_data['district']:
            s.Petrogradsky = True
        if 'Petrodvortsovyy' in post.cleaned_data['district']:
            s.Petrodvortsovyy = True
        if 'Primorskiy' in post.cleaned_data['district']:
            s.Primorskiy = True
        if 'Pushkinskiy' in post.cleaned_data['district']:
            s.Pushkinskiy = True
        if 'Frunzenskiy' in post.cleaned_data['district']:
            s.Frunzenskiy = True
        if 'Tsentralnyy' in post.cleaned_data['district']:
            s.Tsentralnyy = True
        if request.POST['name']:
            s.name = request.POST['name']
        else:
            s.name = 'Шаблон без названия'
        s.save()
        messages.add_message(request, messages.SUCCESS, 'Шаблон сохранен')
        return redirect('main:profile')
    else:
        context = {'form': post}
        return render(request, 'main/index.html', context)

# Применение шаблона поиска
@login_required
def template_search(request, pk):
    st = get_object_or_404(ST, pk=pk)
    initial = {}
    if st.rental:
        initial['type_of_transaction'] = ['rental',]
    if st.purchase:
        initial['type_of_transaction'] += ['purchase',]
    if st.new_building:
        initial['novelty'] = ['new_building',]
    if st.secondary:
        initial['novelty'] += ['secondary',]
    if st.studio:
        initial['number_of_rooms'] = [0,]
    if st.NOF_1:
        initial['number_of_rooms'] += [1,]
    if st.NOF_2:
        initial['number_of_rooms'] += [2,]
    if st.NOF_3:
        initial['number_of_rooms'] += [3,]
    if st.NOF_4:
        initial['number_of_rooms'] += [4,]
    if st.NOF_5:
        initial['number_of_rooms'] += [5,]
    if st.NOF_gte_6:
        initial['number_of_rooms'] += [6,]
    if st.price_from:
        initial['price_from'] = st.price_from
    if st.price_up_to:
        initial['price_up_to'] = st.price_up_to
    if st.Admiralteyskiy:
        initial['district'] = ['Admiralteyskiy',]
    if st.Vasileostrovskiy:
        initial['district'] += ['Vasileostrovskiy',]
    if st.Vyborgskiy:
        initial['district'] += ['Vyborgskiy',]
    if st.Kalininskiy:
        initial['district'] += ['Kalininskiy',]
    if st.Kirovsky:
        initial['district'] += ['Kirovsky',]
    if st.Kolpinsky:
        initial['district'] += ['Kolpinsky',]
    if st.Krasnogvardeisky:
        initial['district'] += ['Krasnogvardeisky',]
    if st.Krasnoselsky:
        initial['district'] += ['Krasnoselsky',]
    if st.Kronshtadtskiy:
        initial['district'] += ['Kronshtadtskiy',]
    if st.Kurortnyy:
        initial['district'] += ['Kurortnyy',]
    if st.Moskovskiy:
        initial['district'] += ['Moskovskiy',]
    if st.Nevsky:
        initial['district'] += ['Nevsky',]
    if st.Petrogradsky:
        initial['district'] += ['Petrogradsky',]
    if st.Petrodvortsovyy:
        initial['district'] += ['Petrodvortsovyy',]
    if st.Primorskiy: 
        initial['district'] += ['Primorskiy',]
    if st.Pushkinskiy: 
        initial['district'] += ['Pushkinskiy',]
    if st.Frunzenskiy: 
        initial['district'] += ['Frunzenskiy',]
    if st.Tsentralnyy: 
        initial['district'] += ['Tsentralnyy',]

    form = UserSearchForm(initial=initial)
    context = {'form':form}
    return render(request, 'main/index.html', context)

# Удаление шаблона поиска
@login_required
def template_delete(request, pk):
    st = get_object_or_404(ST, pk=pk)
    messages.add_message(request, messages.SUCCESS, 'Шаблон "' + st.name + '" удален')
    st.delete()

main/templates/main/activation_done.html
{% extends "layout/basic.html" %}

{% block title %}Активация выполнена{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем успешно активирован.</p>
<p><a href="{% url 'main:login' %}">Войти</a></p>
{% endblock %}

main/templates/main/bad_signature.html
{% extends "layout/basic.html" %}

{% block title %}Ошибка при активации{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Активация пользователя с таким именем прошла неудачно.</p>
<p><a href="{% url 'main:register' %}">Зарегистрироаться повторно</a></p>
{% endblock %}

main/templates/main/change_user_info.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Правка личных данных{% endblock %}

{% block content %}
<h2>Правка личных данных пользователя {{ user.username }}</h2>
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Сохранить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/delete_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Удаление пользователя{% endblock %}

{% block content %}
<h2>Удаление пользователя</h2>
<p>Вы уверены, что хотите удалить пользователя {{ object.username }}?</p>
<form method="post">
	{% csrf_token %}
	{% buttons submit='Удалить' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/index.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block content %}
<form method="post">
	{% csrf_token%}
    <div class="conteiner">
            {% bootstrap_form form %}
    </div>
    {% if not user.is_authenticated and 'captcha' not in request.session %}
    <div class="conteiner">
            {% bootstrap_form captcha  %}
    </div>
    {% endif %}
	<input class="btn btn-primary" type="submit" formaction="{% url 'main:result_avito' %}" value="Поиск на Авито">
	<input class="btn btn-primary" type="submit" formaction="{% url 'main:result_cian' %}" value="Поиск на ЦИАН">
</form>
{% endblock %}

main/templates/main/logout.html
{% extends "layout/basic.html" %}

{% block title %}Выход{% endblock %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли с сайта.</p>
{% endblock %}

main/templates/main/password_reset.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h2>{{ title }}</h2>
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Сбросить пароль' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/password_reset_confirm.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Новый пароль{% endblock %}

{% block content %}
{% if validlink %}
<h2>{{ title }}</h2>
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Сохранить новый пароль' %}{% endbuttons %}
</form>
{% else %}
<p>Интернет-адрес скомпроментирован. Попробуйте сбросить пароль повторно.</p>
{% endif %}
{% endblock %}

main/templates/main/profile.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% load static %}

{% block title %}Профиль пользователя{% endblock %}
{% block content %}
<h1 class="text-center">Профиль пользователя <strong>{{ user.username }}</strong></h1>
{% if user.first_name and user.last_name %}
<p>Здравствуйте, {{ user.first_name }} {{ user.last_name }}!</p>
{% else %}
<p>Здравтсвуйте!</p>
{% endif %}
<h2>Ваши сохраненные шаблоны поиска:</h2>
{% if sts %}
<ul>
	{% for st in sts %}
	<li>
            <h3><a href="{% url 'main:template_search' pk=st.pk %}">{{ st }}</a></h3> 
        <a class="btn btn-primary" href="{% url 'main:template_delete' pk=st.pk %}">Удалить</a>
	</li>
	{% endfor %}
</ul>
{% endif %}
<h2>Ваши сохраненные объявления:</h2>
{% if fas %}
<ul class="list-unstyled">
	{% for fa in fas %}
	<li class="media my-5 p-3 border">
		<a href="{{ fa.link }}" target="_blank">
		{% if fa.image %}
		<img class="mr-3" src="{{ fa.image }}">
		{% else %}
		<img class="mr-3" src="{% static 'main/empty.jpg' %}">
		{% endif %}
		</a>
		<div class="media-body">
			<p class="text-right font-weight-bold">{{ fa.agency }}</p>
			<h3><a href="{{ fa.link }}" target="_blank">{{ fa.title }}</a></h3>
			<p>{{ fa.address }}</p>
			<p class="text-right font-weight-bold">{{ fa.price}}</p>
			<p class="text-right font-italic">{{ fa.date }}</p>
			<p class="text-right"><a href="{% url 'main:favorite_delete' pk=fa.pk  %}">Удалить</a></p>
		</div>
	</li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

main/templates/main/register_done.html
{% extends "layout/basic.html" %}

{% block title %}Регистрация завершена{% endblock %}

{% block content %}
<h2>Регистрация</h2>
<p>Регистрация пользователя завершена.</p>
<p>На адрес электронной почты, указанный пользователем, выслано письмо для активации.</p>
{% endblock %}

main/templates/main/register_user.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация нового пользователя</h2>
<form method="post">
	{% csrf_token %}
	{% bootstrap_form form layout='horizontal' %}
	{% buttons submit='Зарегистрироваться' %}{% endbuttons %}
</form>
{% endblock %}

main/templates/main/result_avito.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% load static %}

{% block title %}Результат поиска{% endblock %}

{% block content %}
<div class="conteiner">
<div class="params border p-3">
        <h2><strong>Выбранные праметры</strong></h2>
<form method="post">
	{% csrf_token%}
	{% bootstrap_form form %}
	{% if user.is_authenticated or 'captcha' in request.session%}
		{{ name }}
        <input class="btn btn-primary" type="submit" formaction="{% url 'main:template_save' %}" value="Сохранить шаблон">
	{% else %}
        {{ captcha }}
    {% endif %}
	<div>
	<input class="btn btn-primary" type="submit" formaction="{% url 'main:result_avito' %}" value="Авито">
	<input class="btn btn-primary" type="submit" formaction="{% url 'main:result_cian' %}" value="ЦИАН">
	</div>
</form>
</div>
<div class="results p-3">
        <h2><strong>Результаты поиска на Авито</strong></h2>
{% if ads %}
<ul class="list-unstyled">
	{% for ad in ads %}
	<li class="media my-5 p-3 border bg-light text-dark">
		<a href="{{ ad.link }}" target="_blank">
		{% if ad.image %}
		<img class="mr-3" src="{{ ad.image }}">
		{% else %}
		<img class="mr-3" src="{% static 'main/empty.jpg' %}" width="250px">
		{% endif %}
		</a>
		<div class="media-body">
			<p class="text-right font-weight-bold">Авито</p>
			<h3><a class="text-primary" href="{{ ad.link }}" target="_blank">{{ ad.title }}</a></h3>
			<p>{{ ad.address }}</p>
			<p class="text-right font-weight-bold">{{ ad.price}}</p>
			<p class="text-right font-italic">{{ ad.date }}</p>
			{% if user.is_authenticated %}
				<form method="post" action="{% url 'main:favorite_save' %}">
					{% csrf_token %}
					<input type="hidden" value="{{ ad.title }}" name="title">
					<input type="hidden" value="{{ ad.link }}" name="link">
					<input type="hidden" value="{{ ad.image }}" name="image">
					<input type="hidden" value="{{ ad.price }}" name="price">
					<input type="hidden" value="{{ ad.address }}" name="address">
					<input type="hidden" value="{{ ad.date }}" name="date">
					<input type="hidden" value="Авито" name="agency">
                    {% buttons submit='Сохранить в избраное' %}{% endbuttons %}
				</form>
			{% endif %}
        </div>
	</li>
{% endfor %}
</ul>
{% endif %}
{% bootstrap_pagination page %}
</div>
</div>
{% endblock %}

main/templates/main/result_cian.html
{% extends "layout/basic.html" %}

{% load bootstrap4 %}
{% load static %}

{% block title %}Результат поиска{% endblock %}

{% block content %}
<div class="conteiner">
<div class="params border p-3">
        <h2><strong>Выбранные праметры</strong></h2>
<form method="post">
	{% csrf_token%}
	{% bootstrap_form form %}
	{% if user.is_authenticated or 'captcha' in request.session %}
		{{ name }}
		<input class="btn btn-primary" type="submit" formaction="{% url 'main:template_save' %}" value="Сохранить шаблон">
    {% else %}
        {{ captcha }}
	{% endif %}
	<div>
	<input class="btn btn-primary" type="submit" formaction="{% url 'main:result_avito' %}" value="Авито">
	<input class="btn btn-primary" type="submit" formaction="{% url 'main:result_cian' %}" value="ЦИАН">
	</div>
</form>
</div>
<div class="results p-3">
        <h2><strong>Результаты поиска на ЦИАН</strong></h2>
{% if ads %}
<ul class="list-unstyled">
	{% for ad in ads %}
	<li class="media my-5 p-3 border bg-light text-dark">
		<a href="{{ ad.link }}" target="_blank">
		{% if ad.image %}
		<img class="mr-3" src="{{ ad.image }}" width="250px">
		{% else %}
		<img class="mr-3" src="{% static 'main/empty.jpg' %}" width="250px">
		{% endif %}
		</a>
		<div class="media-body">
			<p class="text-right font-weight-bold">ЦИАН</p>
			<h3><a class="text-primary" href="{{ ad.link }}" target="_blank">{{ ad.title }}</a></h3>
			<p>{{ ad.address }}</p>
			<p class="text-right font-weight-bold">{{ ad.price}}</p>
			<p class="text-right font-italic">{{ ad.date }}</p>
			{% if user.is_authenticated %}
				<form method="post" action="{% url 'main:favorite_save' %}">
					{% csrf_token %}
					<input type="hidden" value="{{ ad.title }}" name="title">
					<input type="hidden" value="{{ ad.link }}" name="link">
					<input type="hidden" value="{{ ad.image }}" name="image">
					<input type="hidden" value="{{ ad.price }}" name="price">
					<input type="hidden" value="{{ ad.address }}" name="address">
					<input type="hidden" value="{{ ad.date }}" name="date">
					<input type="hidden" value="ЦИАН" name="agency">
					{% buttons submit='Сохранить в избраное' %}{% endbuttons %}
				</form>
			{% endif %}
		</div>
	</li>
{% endfor %}
</ul>
{% endif %}
{% bootstrap_pagination page %}
</div>
</div>
{% endblock %}

main/templates/main/user_is_activated.html
{% extends "layout/basic.html" %}

{% block title %}Пользователь уже активирован{% endblock %}

{% block content %}
<h2>Активация</h2>
<p>Пользователь с таким именем был активирован ранее.</p>
<p><a href="{% url 'main:login' %}">Войти</a></p>
{% endblock %}